services:
  - type: web
    name: async_email_api_demo
    env: ruby
    plan: free
    buildCommand: bundle install
    startCommand: bundle exec rails server
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: masync_email_api_demo-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

